# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Venus Izadi"
description: > # this means to ignore newlines until "email:"
   "I have a Dream!" ... And these are the steps I am taking to accomplish it!

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/Profile-photo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/BgImage3.jpg"

name: 'Dirk Fabisch'
author: 'Dirk Fabisch'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://myblog.***.***" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	linkedin
    url:	https://www.linkedin.com/in/venus-izadi/
    desc: Follow me on Linkedin
    share_url: https://www.linkedin.com/in/venus-izadi/
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/Venus-Izadi
    desc:	My github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
